version: "3"

services:
  service1:
    build: ./service1
    ports:
      - 5000:5000
    networks:
      - default

    depends_on:
      - db
      - db-manager
    environment:
      - POSTGRES_DB_PASSWORD=password
      - POSTGRES_DB_USER=admin
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db

  service2:
    build: ./service2
    ports:
      - 5001:5001
    environment:
      - POSTGRES_DB_PASSWORD=password
      - POSTGRES_DB_USER=admin
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db

    depends_on:
      - service1
      - db
      - db-manager

  web:
    build: ./web
    volumes:
      - ./web:/app
      - ./web/public/:/app/public
      - "/app/node_modules"
    depends_on:
      - service1
      - service2
      - db-manager
      - db
    environment:
      - ENV=test
    tty: true

    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - service1
      - service2
      - db

  db-manager:
    build: ./db-manager
    depends_on:
      - db
    environment:
      - POSTGRES_DB_PASSWORD=password
      - POSTGRES_DB_USER=admin
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
